# Demo for remote provisioning of windows machine

- hosts: windows
  tasks:
   - name: Ensure connectivity.
     win_ping:
   - name: Add setting to change context menu to classic mode.
     win_shell: REG ADD "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /VE /T REG_SZ /D "" /F
   - name: Install Vscode. 
     win_chocolatey: 
       name: vscode
       state: latest
   - name: Reboot Machine.
     win_reboot:
